package com.techleads.app;

public interface DBQueries {

	
	
	String SELECT_ALL_LOGINS="SELECT  EMP_ID,  NAME  FROM  EMP_LOGIN";
	String SELECT_LOGINS_BY_ID="SELECT  EMP_ID,  NAME  FROM  EMP_LOGIN WHERE EMP_ID=?";
	String INSERT_LOGINS="INSERT INTO EMP_LOGIN (EMP_ID, NAME) VALUES (?, ?)";
	String UPD_LOGIN_BY_ID="UPDATE EMP_LOGIN SET NAME=?  WHERE EMP_ID=?";
	String DEL_LOGIN_BY_ID="DELETE FROM EMP_LOGIN WHERE EMP_ID=?";
	
	
	String INSERT_LOG_DTLS="INSERT INTO LOG_DTLS (ID ,NAME ,ACTUAL_SHIFT ,LOGIN_DTE ,LOGIN_TIME ,LOGOFF_TIME ,COMMENTS ) VALUES(?,?,?,?,?,?,?)";
	
	String SELECT_ALL_LOG_DTLS="SELECT ID ,NAME ,ACTUAL_SHIFT ,LOGIN_DTE ,LOGIN_TIME ,LOGOFF_TIME ,COMMENTS FROM LOG_DTLS";
	String SELECT_LOG_DTLS_BY_ID="SELECT ID ,NAME ,ACTUAL_SHIFT ,LOGIN_DTE ,LOGIN_TIME ,LOGOFF_TIME ,COMMENTS FROM LOG_DTLS WHERE ID=?";
	
	String DEL_LOG_DTLS_BY_ID="DELETE FROM LOG_DTLS WHERE ID=?";
	
	String UPD_LOG_DTLS_BY_ID="UPDATE LOG_DTLS SET ACTUAL_SHIFT=?, LOGIN_TIME =?, LOGOFF_TIME=?, COMMENTS =? WHERE ID=?";
}
