package com.techleads.app;

public interface DBQueries {

	String SHIFT_101="12 pm to 1:30 am";
	String SHIFT_102="12 pm to 9 pm";
	String SHIFT_103="4pm to 1 am";
	String SHIFT_104="1pm to 10pm";
	String SHIFT_105="5 am to 11:30 am & 7:30 pm to 11 pm";
	String SHIFT_106="2 pm to 11 pm";
	
	
	String SELECT_ALL_LOGINS="SELECT  EMP_ID,  NAME, CREATED_DTE, LAST_UPDATED_DTE  FROM  EMP_LOGIN";
	String SELECT_LOGINS_BY_ID="SELECT  EMP_ID,  NAME, CREATED_DTE, LAST_UPDATED_DTE FROM  EMP_LOGIN WHERE EMP_ID=?";
	String INSERT_LOGINS="INSERT INTO EMP_LOGIN (EMP_ID, NAME, CREATED_DTE, LAST_UPDATED_DTE ) VALUES (?, ?, ?, ?)";
	String UPD_LOGIN_BY_ID="UPDATE EMP_LOGIN SET NAME=?, LAST_UPDATED_DTE=?  WHERE EMP_ID=?";
	String DEL_LOGIN_BY_ID="DELETE FROM EMP_LOGIN WHERE EMP_ID=?";
	
	
	String INSERT_LOG_DTLS="INSERT INTO EMP_LOGIN_DTLS (ID, ACTUAL_SHIFT, LOGIN_DATE, LOGIN_TIME, LOGOFF_TIME, COMMENTS, CREATED_DTE, LAST_UPDATED_DTE, EMP_ID) VALUES (EMP_DTLS_ID.NEXTVAL, ?, ?, ?, ?, ?, ?, ?, ?)";
	
	String SELECT_ALL_LOG_DTLS="SELECT D.ID, D.ACTUAL_SHIFT, D.LOGIN_DATE, D.LOGIN_TIME, D.LOGOFF_TIME, D.COMMENTS, D.CREATED_DTE, D.LAST_UPDATED_DTE, D.EMP_ID FROM EMP_LOGIN_DTLS D";
	String SELECT_LOG_DTLS_BY_EMP_ID="SELECT D.ID, D.ACTUAL_SHIFT, D.LOGIN_DATE, D.LOGIN_TIME, D.LOGOFF_TIME, D.COMMENTS, D.CREATED_DTE, D.LAST_UPDATED_DTE, D.EMP_ID FROM EMP_LOGIN_DTLS D WHERE D.EMP_ID=?";
	String DEL_LOG_DTLS_BY_ID="DELETE FROM LOG_DTLS WHERE ID=?";
	String UPD_LOG_DTLS_BY_ID="UPDATE EMP_LOGIN_DTLS SET ACTUAL_SHIFT=?, LOGIN_TIME =?, LOGOFF_TIME=?, COMMENTS =?, LAST_UPDATED_DTE=?  WHERE ID = ? AND EMP_ID=?";
}
